# Problem 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.


# We define an iterator giving every fibonacci number
class fibonacci:
    def __iter__(self):
        self.a = 0
        self.previous = [1, 2]
        return self
    
    def __next__(self):
        if self.a == 0:
            self.a = 1
            self.previous = [1, 2]
            return 1
        if self.a == 1:
            self.a = 2
            self.previous = [1, 2]
            return 2
        elif self.a == 2:
            self.a = 3
            self.previous = [1, 2]
            return 3
        else:
            self.previous[0] = self.previous[1]
            self.previous[1] = self.a
            self.a = self.previous[0] + self.previous[1]
            return self.a

def main():
    fibonacci_numbers = iter(fibonacci())
    result = 0
    while True:
        number = next(fibonacci_numbers)
        if number % 2 == 0:
            result = result + number
        if number >= 4000000:
            break
    print(result)
    
    
if __name__ == "__main__":
    main()